"""add missing tables

Revision ID: 3d4645e08386
Revises: 817c8fe04b7c
Create Date: 2025-12-10 20:09:29.322220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d4645e08386'
down_revision: Union[str, Sequence[str], None] = '817c8fe04b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authz_audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('identity_audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.drop_table('identity_audit_log')
    op.drop_table('authz_audit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authz_audit_log',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('authz_audit_log_pkey'))
    )
    op.create_table('identity_audit_log',
    sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('identity_audit_log_pkey'))
    )
    op.drop_table('identity_audit_logs')
    op.drop_table('authz_audit_logs')
    # ### end Alembic commands ###
