"""Initial migration

Revision ID: 817c8fe04b7c
Revises: 
Create Date: 2025-12-10 17:02:55.881335

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '817c8fe04b7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('authz_audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('identity_audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('token_signing_keys',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=10), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('private_key_pem_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('machine_clients',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('certificate_thumbprint', sa.String(length=64), nullable=True),
    sa.Column('certificate_serial', sa.String(length=64), nullable=True),
    sa.Column('certificate_not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(certificate_thumbprint IS NULL AND certificate_not_after IS NULL) OR (certificate_thumbprint IS NOT NULL AND certificate_not_after IS NOT NULL)', name='cert_fields_together'),
    sa.ForeignKeyConstraint(['owner_id'], ['admin_users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('certificate_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('certificate_pem', sa.Text(), nullable=True),
    sa.Column('private_key_pem_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('download_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['admin_users.user_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['machine_clients.subject_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['admin_users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('idx_one_pending_per_client', 'certificate_requests', ['client_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('issued_certificates',
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('thumbprint', sa.String(length=64), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['machine_clients.subject_id'], ),
    sa.PrimaryKeyConstraint('certificate_id'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issued_certificates')
    op.drop_index('idx_one_pending_per_client', table_name='certificate_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('certificate_requests')
    op.drop_table('machine_clients')
    op.drop_table('token_signing_keys')
    op.drop_table('subjects')
    op.drop_table('identity_audit_log')
    op.drop_table('authz_audit_log')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
